### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by burtonboucher** [alan412/LearnJavaForFTC#43]
# Date on version you are commenting on
June 10, 2020

# Section you are commenting on
7.2

# Questions
“ While RUN_TO_POSITION can be very handy for single motors, we recommend AGAINST using it in a drive train because the different speeds for the different wheels trying to get to a position can cause wacky side effects.”.   

Isn’t this supposed to be configurable using PID? 
What side effects?
When do side effects occur? Startup, stopping, steady state, or all?

**Comment by alan412** [comment]
Yes, this uses PID.   The side effects are that each motor has speeds depending on how far away it is from a position.  If you go the same number of "ticks" on two wheels but not at the same speed, you won't end up at the same place on your robot (due to skid) as you will if you work with both of them at the same speed.   Let me think about how to word this more simply and I'll put this in.
