### ISSUE TITLE
Better `listings` configuration

### ISSUE THREAD

**Issue by guineawheek** [alan412/LearnJavaForFTC#49]
# Date on version you are commenting on
Aug 11, 2020

# Section you are commenting on
3.2

# Comments
I think it would make the book much more readable especially in pdf form if the listings configuration used in the book's LaTeX used a `\lstset` that enabled color support and thus syntax highlighting. 

Also, would it be possible to publish the source tex files in the repo? I understand if that is not possible.

**Comment by alan412** [comment]
It is using syntax highlighting for the book, but only in black and white since it is the same source that goes into the paperback edition and dithered colors make that harder tor read.

While it is possible to publish the source files, I don't understand why that would be of a benefit.  I actually use Lyx (www.lyx.org) as a front end to latex instead of working on the latex directly.
