### ISSUE TITLE
Issues with chapters 15 and 16

### ISSUE THREAD

**Issue by Windwoes** [alan412/LearnJavaForFTC#52]
# Date on version you are commenting on
May 1 2022

# Section you are commenting on
15 and 16

# Comments

 - Rumble support was actually added in SDK v7.0, not 6.0 :')
 - 16.1: "Luckily for OpenCV, there is a project called OpenCV." Typo here I think. Also in the next sentence *"It is very common for people to forget to copy the openCV library onto the Android device"* It would probably be better to specify that it's the native shared library (`.so`) file specifically that you're talking about.
 - 16.2: *"In our start, we stop the streaming"* - `stopStreaming()` is a blocking call, would suggest `closeCameraDeviceAsync()` instead.
 - 16.2.2: *" (It is called for EVERY frame in the video, so it needs to do as little as possible.)"* - possibly a bit misleading - taking too long inside processFrame() will not cause a "lag stackup" or anything. The stream is double buffered so if you miss one inter-frame deadline the next frame is still stored for you to work on immediately, but beyond that the frames are simply dropped.
 - 16.6: In your `FirstPipelineRevised` you are releasing `hsvMat` and `input` every time around processFrame; this is not required. You have set up `hsvMat` as an instance variable rather than a local variable, so the framebuffer will be preserved and re-used across calls to processFrame; this is good and reduced memory pressure compared to allocing and freeing it every time. Also, you should never call `release()` on `input`.

**Comment by alan412** [comment]
* Wrong version of SDK - fixed
* 16.1 comment - fixed
* 16.2 - we actually use stopStreaming because it doesn't close the connection to your camera which allows you to start it again later if needed with less lag.    Is there a non-blocking call that stops the streaming but doesn't close the device?
* 16.2.2 - I modified the text.  Please let me know what you think
* 16.6 - If you remove either of those release() then the pipeline has a memory leak.   You can see it by running them in the simulator and checking memory usage and watch it climb.
    * For the input mat, my understanding (which may not be correct) is that if you return a different mat than the one that was passed to you then you need to release the one that was passed to you and the one you return will continue in the processing.
    * For the HSV mat, you need to release it since it is being filled by the cvtColor call.
(It is possible and even likely that there is something I don't understand here.   Most of my java knowledge is as an FTC coach or FRC mentor.)

Also, if you'll give me your name and any associated FTC team then I'll be happy to add you to the Credits.   I really appreciate your taking the time to give feedback!!

**Comment by alan412** [comment]
Thank you very much!!   I didn't know about extractChannel - that is a MUCH cleaner way of doing it.    What is your name so I can put you in the Credits?

**Comment by Windwoes** [comment]
Michael - 4634 alum
